version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - :/$HOME/workspace/redis